### shows all actors
GET http://localhost:3000/actors.json
Content-Type: application/json

### shows single actor
GET http://localhost:3000/actor/11.json
Content-Type: application/json

### creates actor
POST http://localhost:3000/actor.json
Content-Type: application/json

{
  "first_name": "Viola",
  "last_name": "Davis",
  "known_for": "How to Get Away With Murder",
  "gender": "female",
  "age": "56"
}

### updates actor
PATCH http://localhost:3000/actor/9.json
Content-Type: application/json

{
  "age": "47",
  "gender": "Female"
}

### deletes actor
DELETE  http://localhost:3000/actor/6
Content-Type: application/json