### shows all movies
GET http://localhost:3000/movies.json
Content-Type: application/json

### shows single movie
GET http://localhost:3000/movie/2.json
Content-Type: application/json

### creates movie
POST http://localhost:3000/movie.json
Content-Type: application/json

{
  "title": "Avatar",
  "year": "2009",
  "plot": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
  "director": "James Cameron",
  "english": "true"
}

### updates movie
PATCH http://localhost:3000/movie/3.json
Content-Type: application/json

{
  "english": "true",
  "director": "Ridley Scott"
}

### deletes movie
DELETE  http://localhost:3000/movie/5.json
Content-Type: application/json