### shows all movies
GET http://localhost:3000/movies.json
Content-Type: application/json

### shows single movie
GET http://localhost:3000/movie/2.json
Content-Type: application/json

### creates movie
POST http://localhost:3000/movie.json
Content-Type: application/json

{
  "title": "Hereditary",
  "year": "2018",
  "plot": "American miniature artist Annie Graham lives in Utah with her Irish psychiatrist husband Steve, their 16-year-old son Peter, and their 13-year-old daughter Charlie.",
  "director": "Ari Aster",
  "english": "true"
}

### updates movie
PATCH http://localhost:3000/movie/3.json
Content-Type: application/json

{
  "english": "true",
  "director": "Ridley Scott"
}

### deletes movie
DELETE  http://localhost:3000/movie/5.json
Content-Type: application/json